controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: ../src/Api/Action/
    type: attribute
    prefix: api

api_login_check:
    path: /api/login
